# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

platform :ios, '8.0'
use_frameworks!

pod "FFastlib"

target 'fast-template' do

end

target 'fast-templateTests' do

end

target 'fast-templateUITests' do

end

